name: Base with plugin.Gists
on:
  #Schedule daily updates
  schedule: [{ cron: "0 0 * * *" }]
  #Run workflow manually
  workflow_dispatch:
  #Run workflow when pushing on master/main
  push: { branches: ["master", "main"] }
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          #Token
          token: ${{ secrets.METRICS_TOKEN }}

          #Options
          config_octicon: yes
          config_timezone: Europe/Moscow

          #Configure
          filename: metrics.base.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: header, activity, community, repositories, metadata
          plugin_gists: yes
