name: plugin.Languages
on:
  #Schedule daily updates
  schedule: [{ cron: "0 0 * * *" }]
  #Run workflow manually
  workflow_dispatch:
  #Run workflow when pushing on master/main
  push: { branches: ["master", "main"] }
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          #Token
          token: ${{ secrets.METRICS_TOKEN }}

          #Options
          config_octicon: yes
          config_timezone: Europe/Moscow

          #Configure
          filename: metrics.plugin.languages.svg
          base: ""
          plugin_languages: yes
          # plugin_languages_ignored: >-
          #   html, css, tex, less, dockerfile, makefile, qmake, lex, cmake, shell,
          #   gnuplot
          plugin_languages_indepth: yes
          plugin_languages_details: lines, bytes-size
          plugin_languages_limit: 4
          plugin_languages_analysis_timeout: 15
