name: plugin.Achievements
on:
  #Schedule daily updates
  schedule: [{ cron: "0 0 * * *" }]
  #Run workflow manually
  workflow_dispatch:
  #Run workflow when pushing on master/main
  push: { branches: ["master", "main"] }
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          #Token
          token: ${{ secrets.METRICS_TOKEN }}

          #Options
          config_octicon: yes
          config_timezone: Europe/Moscow

          #Configure
          filename: metrics.plugin.achievements.svg
          base: ""
          plugin_achievements: yes
          plugin_achievements_only: sponsor, maintainer, octonaut
