name: plugin.Rss
on:
  #Schedule daily updates
  schedule: [{ cron: "0 0 * * *" }]
  #Run workflow manually
  workflow_dispatch:
  #Run workflow when pushing on master/main
  push: { branches: ["master", "main"] }
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          #Configure
          filename: metrics.plugin.rss.svg
          base: ""
          plugin_rss: yes
          plugin_rss_limit: 4
          plugin_rss_source: https://potatoenergy.is-a.dev/posts/index.xml
